### ISSUE TITLE
Docker compose config not worked, run failed

### ISSUE THREAD

**Issue by tallot13** [chaskiq/chaskiq#113]
docker-compose up webpacker
Creating chaskiq-master_webpacker_1 ... done
Attaching to chaskiq-master_webpacker_1
webpacker_1  | /usr/local/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:495:in `validate_ruby!': Your Ruby version is 2.6.3, but your Gemfile specified 2.6.5 (Bundler::RubyVersionMismatch)
webpacker_1  | 	from /usr/local/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:470:in `validate_runtime!'
webpacker_1  | 	from /usr/local/lib/ruby/site_ruby/2.6.0/bundler.rb:143:in `setup'
webpacker_1  | 	from /usr/local/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `block in <top (required)>'
webpacker_1  | 	from /usr/local/lib/ruby/site_ruby/2.6.0/bundler/ui/shell.rb:136:in `with_level'
webpacker_1  | 	from /usr/local/lib/ruby/site_ruby/2.6.0/bundler/ui/shell.rb:88:in `silence'
webpacker_1  | 	from /usr/local/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
webpacker_1  | 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
webpacker_1  | 	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
webpacker_1  | 	from ./bin/webpack-dev-server:12:in `<main>'
chaskiq-master_webpacker_1 exited with code 1

**Comment by tallot13** [comment]
docker-compose up rails
chaskiq-master_postgres_1 is up-to-date
chaskiq-master_redis_1 is up-to-date
Starting chaskiq-master_rails_1 ... done
Attaching to chaskiq-master_rails_1
rails_1      | Your Ruby version is 2.6.3, but your Gemfile specified 2.6.5
chaskiq-master_rails_1 exited with code 18

**Comment by tallot13** [comment]
after changed docker-compose.yml to 2.6.5
docker-compose up rails
chaskiq-master_redis_1 is up-to-date
chaskiq-master_postgres_1 is up-to-date
Recreating chaskiq-master_rails_1 ... done
Attaching to chaskiq-master_rails_1
rails_1      | Could not find rake-12.3.3 in any of the sources
rails_1      | Run `bundle install` to install missing gems.
chaskiq-master_rails_1 exited with code 7


docker-compose up webpacker
Recreating chaskiq-master_webpacker_1 ... done
Attaching to chaskiq-master_webpacker_1
webpacker_1  | ./bin/webpack-dev-server: No such file or directory - getcwd (Errno::ENOENT)
chaskiq-master_webpacker_1 exited with code 1

**Comment by DavidGOrtega** [comment]
Agree, I have indeed gone a bit further to. receive

```
PG::ConnectionBad: FATAL:  database "hermes" does not exist
```

by rails and the webapacker

**Comment by michelson** [comment]
new instructions for build and use docker-compose on development at https://dev.chaskiq.io/en/articles/docker-for-development

please reopen if you encounter issues

**Comment by DavidGOrtega** [comment]
running step 2

```
docker-compose run rails rake db:create
```
```
Database 'hermes' already exists
could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Couldn't create 'hermes_test' database. Please check your configuration.
rake aborted!
ActiveRecord::NoDatabaseError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

Have you run the instructions successfully?

**Comment by DavidGOrtega** [comment]
Issue is not mine so I can't reopen it. Can you please @michelson reopen it?

**Comment by michelson** [comment]
the error says that the database already exists, so it's already there, but the connection for the test database is the one who throw the error

**Comment by roshanjonah** [comment]
I am getting the same error...

chatadmino@chaskiq-srv1:~/chaskiq$ docker-compose run rails rake db:create
Starting chaskiq_postgres_1 ... done
Starting chaskiq_redis_1    ... done
Could not find rake-13.0.1 in any of the sources
Run `bundle install` to install missing gems.

**Comment by jalberto** [comment]
you need this in the `test`section of `database.yml` file:

```
  url: <%= ENV['DATABASE_URL'] %>
```

**Comment by nicolenix** [comment]
I am also following this guide:
https://dev.chaskiq.io/en/articles/docker-for-development

Getting this error:

![image](https://user-images.githubusercontent.com/66929292/84610596-f7c97780-ae6f-11ea-9330-81fc70850ac3.png)

```
FATAL:  role "postgres" does not exist
Couldn't create 'postgres' database. Please check your configuration.
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "postgres" does not exist
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:889:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:912:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:873:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:595:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:439:in `connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1121:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_handling.rb:238:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_handling.rb:206:in `connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/usr/local/bundle/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'

Caused by:
PG::ConnectionBad: FATAL:  role "postgres" does not exist
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:889:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:912:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:873:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:595:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:439:in `connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1121:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_handling.rb:238:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/connection_handling.rb:206:in `connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/gems/activerecord-6.0.2/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/usr/local/bundle/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

**Comment by geonizeli** [comment]
@nicolenix Same error here ... and my docker was completely clean. I tried to correct the configuration here but was unsuccessful.

**Comment by harrisyn** [comment]
same issue as @nicolenix

**Comment by jimit-indianic** [comment]
I am also facing the same issue as @harrisyn @nicolenix 

```
$ docker-compose run rails rake db:create

Starting reactjs-chask_postgres_1 ... done
Starting reactjs-chask_redis_1    ... done
FATAL:  role "postgres" does not exist
Couldn't create 'postgres' database. Please check your configuration.
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "postgres" does not exist
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:189:in `connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/usr/local/bundle/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'

Caused by:
PG::ConnectionBad: FATAL:  role "postgres" does not exist
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/connection_handling.rb:189:in `connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/usr/local/bundle/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

**Comment by WEBudoGT** [comment]
Same as @jimit-indianic

**Comment by pucilpet** [comment]
I managed to fix the "FATAL:  role "postgres" does not exist" by creating the postgres role manually.

So after docker-compose run rails rake db:create

I ran these commands:

`docker container list`

Copy the postgres containers id

Then `docker exec -it postgrescontainerid /bin/bash`

`createuser -s -r postgres`

Then you should be able to login with `psql -U postgres`

and continue with the installation flow (after first exiting from the postgres container).

**Comment by michelson** [comment]
Hi, please try the master branch, I've updated the docker-compose to work properly with postgres.
sorry for the delay on this, it also uses ruby 2.7.1

**Comment by eduardolagares** [comment]
I'm trying to use docker-compose but it is not working. Follow the error

```chaskiq git:(master) docker-compose up rails
Building rails
[+] Building 5.8s (16/18)                                                                                                                                                                                      
 => [internal] load build definition from Dockerfile.development                                                                                                                                          0.0s
 => => transferring dockerfile: 49B                                                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                                                         0.0s
 => => transferring context: 35B                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/ruby:2.7.1-slim-buster                                                                                                                                 1.5s
 => [ 1/14] FROM docker.io/library/ruby:2.7.1-slim-buster@sha256:ff48e3b5870c4472172b1e9ddfba36ffda399f8378b70d22125b9c31cc7edb54                                                                         0.0s
 => [internal] load build context                                                                                                                                                                         0.0s
 => => transferring context: 128B                                                                                                                                                                         0.0s
 => CACHED [ 2/14] RUN apt-get update -qq   && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends     build-essential     gnupg2     curl     less     git     imagemagick     z  0.0s
 => CACHED [ 3/14] RUN curl -sSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -   && echo 'deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main' 11 > /etc/apt/sources.list  0.0s
 => CACHED [ 4/14] RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -                                                                                                                            0.0s
 => CACHED [ 5/14] RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -   && echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list                    0.0s
 => CACHED [ 6/14] COPY .dockerdev/Aptfile /tmp/Aptfile                                                                                                                                                   0.0s
 => CACHED [ 7/14] RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade &&   DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends     libpq-dev     p  0.0s
 => CACHED [ 8/14] RUN gem update --system &&     gem install bundler:2.0.2                                                                                                                               0.0s
 => CACHED [ 9/14] RUN mkdir -p /app                                                                                                                                                                      0.0s
 => CACHED [10/14] WORKDIR /tmp                                                                                                                                                                           0.0s
 => CACHED [11/14] COPY Gemfile Gemfile.lock /tmp/                                                                                                                                                        0.0s
 => ERROR [12/14] RUN bundle install -j 4 --retry 3                                                                                                                                                       4.2s
------                                                                                                                                                                                                         
 > [12/14] RUN bundle install -j 4 --retry 3:                                                                                                                                                                  
#16 0.500 Warning: the running version of Bundler (2.0.2) is older than the version that created the lockfile (2.1.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.                                                                                                                                                                                                              
#16 0.587 The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.                                                                                     
#16 1.539 Fetching gem metadata from https://rubygems.org/........
#16 3.947 Your bundle is locked to mimemagic (0.3.5), but that version could not be found
#16 3.947 in any of the sources listed in your Gemfile. If you haven't changed sources,
#16 3.947 that means the author of mimemagic (0.3.5) has removed it. You'll need to update
#16 3.947 your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
#16 3.947 in order to install.
------
executor failed running [/bin/sh -c bundle install -j ${BUNDLE_JOBS} --retry ${BUNDLE_RETRY}]: exit code: 7
ERROR: Service 'rails' failed to build
```
**scenery:**
- I did it on branch master

**My tries to fix:**
* Change bundler version fix the warning about bundler but not resolved tzinfo.
* tzinfo-data I tried to remove but it is dependence on the mimemagic.


**SOLUTION** 

Apparently mimemagic gems were removed today let only 0.3.6 and 0.4.0. (https://github.com/rails/rails/issues/41750). I just change on gemfile to fix gem 'mimemagic', '0.3.6' and it built.

**Comment by michelson** [comment]
Oh yes, it happened that mimemagic author has yanked the dependences , bundle update will be necessary. `bundle exec update mimemagic` I will update this asap

https://github.com/zRedShift/mimemagic/issues/4#issuecomment-804793510
