### ISSUE TITLE
Error build with heroku

### ISSUE THREAD

**Issue by kang28ivan** [chaskiq/chaskiq#202]
I am still curious to successfully install chaskiq, but to this day no I have never managed to install, all the tutorial methods written in my documentation have followed in detail but it really is very difficult and nothing works until it's finished.

Now I try install again with heroku, the error still same as previously

```
root@platform:~/chaskiq# heroku run rails admin_generator
Running rails admin_generator on ⬢ serene-reaches-59471... up, run.1753 (Free)
W, [2020-07-25T15:19:37.765395 #4]  WARN -- [Bugsnag]: No valid API key has been set, notifications will not be sent
rails aborted!
ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/associations/collection_association.rb:337:in `_create_record'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/associations/has_many_association.rb:115:in `_create_record'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/associations/association.rb:195:in `create'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/associations/collection_proxy.rb:347:in `create'
/app/app/models/app.rb:219:in `add_admin'
/app/lib/tasks/admin_generator.rake:4:in `block in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/app/bin/rails:6:in `<main>'
Tasks: TOP => admin_generator
(See full trace by running task with --trace)
```

Has anyone successfully installed chaskiq? I searched for tutorials on google, also very minimal users of chaskiq.
If this still doesn't work and stuck, it's likely I'll leave Chaskiq and search for something easier

Thank you.

**Comment by michelson** [comment]
did you run rails db:migrate before run the admin_generator ?

**Comment by kang28ivan** [comment]
> did you run rails db:migrate before run the admin_generator ?

Yes, I followed the step by step in the tutorial in the documentation

**Comment by kang28ivan** [comment]
> did you run rails db:migrate before run the admin_generator ?

```
root@platform:~/chaskiq# heroku run rails db:migrate
Running rails db:migrate on ⬢ serene-reaches-59471... up, run.5246 (Free)
W, [2020-07-25T16:45:11.661314 #4]  WARN -- [Bugsnag]: No valid API key has been set, notifications will not be sent
root@platform:~/chaskiq# heroku run rails db:seed
Running rails db:seed on ⬢ serene-reaches-59471... up, run.4964 (Free)
W, [2020-07-25T16:46:14.013075 #4]  WARN -- [Bugsnag]: No valid API key has been set, notifications will not be sent
root@platform:~/chaskiq# heroku run rails admin_generator
Running rails admin_generator on ⬢ serene-reaches-59471... up, run.7800 (Free)
W, [2020-07-25T16:47:36.518696 #4]  WARN -- [Bugsnag]: No valid API key has been set, notifications will not be sent
rails aborted!
ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/associations/collection_association.rb:337:in `_create_record'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/associations/has_many_association.rb:115:in `_create_record'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/associations/association.rb:195:in `create'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/associations/collection_proxy.rb:347:in `create'
/app/app/models/app.rb:219:in `add_admin'
/app/lib/tasks/admin_generator.rake:4:in `block in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/app/bin/rails:6:in `<main>'
Tasks: TOP => admin_generator
(See full trace by running task with --trace)
```

What's wrong with the log above? 🙏

**Comment by michelson** [comment]
did you set the ADMIN_EMAIL & ADMIN_PASSWORD env var on heroku ?

**Comment by kang28ivan** [comment]
Sure, I already set from the first
![Screenshot_2](https://user-images.githubusercontent.com/53988458/88471962-42dfab80-cf41-11ea-8784-ebc7fec224ec.png)

**Comment by michelson** [comment]
Can you invite me at your heroku app? My email is Miguelmichelson@gmail.com
, i can investigate further

**Comment by kang28ivan** [comment]
Already invited, please check.

**Comment by michelson** [comment]
Hi , you have not configured the app properly , you have to set the env vars . 

please try to install from the [heroku button](https://heroku.com/deploy?template=https://github.com/chaskiq/chaskiq/tree/master)  where you will asked for to fill those required vars on the installation step

**Comment by kang28ivan** [comment]
> Hi , you have not configured the app properly , you have to set the env vars .
> 
> please try to install from the [heroku button](https://heroku.com/deploy?template=https://github.com/chaskiq/chaskiq/tree/master) where you will asked for to fill those required vars on the installation step

Ok thank you, I will try reinstall again.
I just followed the instructions according to the documentation, I think it was automatically generated when pushed to heroku

**Comment by kang28ivan** [comment]
> Hi , you have not configured the app properly , you have to set the env vars .
> 
> please try to install from the [heroku button](https://heroku.com/deploy?template=https://github.com/chaskiq/chaskiq/tree/master) where you will asked for to fill those required vars on the installation step

Already finish deploy with heroku but still error "**We're sorry, but something went wrong.**" https://boiling-shore-21480.herokuapp.com/

```
2020-07-26T10:15:35.485606+00:00 app[web.1]: * Listening on tcp://0.0.0.0:55408
2020-07-26T10:15:35.485813+00:00 app[web.1]: Use Ctrl-C to stop
2020-07-26T10:15:35.841195+00:00 heroku[web.1]: State changed from starting to up
2020-07-26T10:16:07.791016+00:00 app[web.1]: F, [2020-07-26T10:16:07.790867 #7] FATAL -- : [acf816f5-3ffa-4d18-abde-717fd8c03d3a]   
2020-07-26T10:16:07.791085+00:00 app[web.1]: [acf816f5-3ffa-4d18-abde-717fd8c03d3a] NoMethodError (undefined method `app' for nil:NilClass):
2020-07-26T10:16:07.791087+00:00 app[web.1]: [acf816f5-3ffa-4d18-abde-717fd8c03d3a]   
2020-07-26T10:16:07.791097+00:00 app[web.1]: [acf816f5-3ffa-4d18-abde-717fd8c03d3a] app/controllers/articles_controller.rb:15:in `messenger_data'
2020-07-26T10:16:07.791097+00:00 app[web.1]: [acf816f5-3ffa-4d18-abde-717fd8c03d3a] app/controllers/articles_controller.rb:7:in `show'
2020-07-26T10:16:07.793361+00:00 heroku[router]: at=info method=GET path="/" host=boiling-shore-21480.herokuapp.com request_id=acf816f5-3ffa-4d18-abde-717fd8c03d3a fwd="36.83.128.83" dyno=web.1 connect=0ms service=156ms status=500 bytes=1905 protocol=https
2020-07-26T10:16:08.230918+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=boiling-shore-21480.herokuapp.com request_id=a76de4e0-02ef-453a-aed8-8f860be07169 fwd="36.83.128.83" dyno=web.1 connect=0ms service=9ms status=200 bytes=221 protocol=https
2020-07-26T10:17:03.275416+00:00 heroku[router]: at=info method=GET path="/" host=boiling-shore-21480.herokuapp.com request_id=57408121-0015-48ce-b4a6-513acd80615f fwd="36.83.128.83" dyno=web.1 connect=0ms service=178ms status=500 bytes=1905 protocol=https
2020-07-26T10:17:03.273193+00:00 app[web.1]: F, [2020-07-26T10:17:03.273058 #7] FATAL -- : [57408121-0015-48ce-b4a6-513acd80615f]   
2020-07-26T10:17:03.273214+00:00 app[web.1]: [57408121-0015-48ce-b4a6-513acd80615f] NoMethodError (undefined method `app' for nil:NilClass):
2020-07-26T10:17:03.273215+00:00 app[web.1]: [57408121-0015-48ce-b4a6-513acd80615f]   
2020-07-26T10:17:03.273216+00:00 app[web.1]: [57408121-0015-48ce-b4a6-513acd80615f] app/controllers/articles_controller.rb:15:in `messenger_data'
2020-07-26T10:17:03.273217+00:00 app[web.1]: [57408121-0015-48ce-b4a6-513acd80615f] app/controllers/articles_controller.rb:7:in `show'
2020-07-26T10:14:34.000000+00:00 app[heroku-redis]: source=REDIS addon=redis-rectangular-61014 sample#active-connections=1 sample#load-avg-1m=0.09 sample#load-avg-5m=0.135 sample#load-avg-15m=0.16 sample#read-iops=0 sample#write-iops=0.082873 sample#memory-total=15664256kB sample#memory-free=10683236kB sample#memory-cached=1788376kB sample#memory-redis=313968bytes sample#hit-rate=1 sample#evicted-keys=0
```

**Comment by tabrza** [comment]
@kang28ivan - did you manage to figure this out? i'm trying to deploy this but could use a little help.. the deploy from heroku button requires all config vars to be completed 
could use a little guidance around the config vars, where you pulled them from and of course, the secret_token as i don't see this in the code base. 

@michelson - any help/guidance from you would be extremely appreciated!

**Comment by michelson** [comment]
Hi , probably need to add the HOST and WS config env var. please refer to the documentation on https://dev.chaskiq.io/en/articles/deploy-on-heroku
