### ISSUE TITLE
Getting blank page on installing and running it on Mac

### ISSUE THREAD

**Issue by vivec80** [chaskiq/chaskiq#214]
Hi Miguel,

First, great job in making this platform. No words to express how excited I am when I got to know of this and so eager to try this :).
I could not find a place to ask for the issue I am facing hence writing it here:
I followed the Mac instructions to the tee but still I am unable to get it up and running locally. I am getting a blank page when i hit my localhost. There is no error that I see as well. Below is my console snapshot:
Started GET "/" for ::1 at 2020-09-05 19:07:16 +0530
Processing by HomeController#show as HTML
  Rendering home/show.erb within layouts/application
  Rendered home/show.erb within layouts/application (Duration: 4.0ms | Allocations: 204)
[Webpacker] Everything's up-to-date. Nothing to do
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 9174ms (Views: 9158.8ms | ActiveRecord: 0.0ms | Allocations: 6729802)

Not delivering sessions due to an invalid api_key

Wondering if this has got anything to do with any api key that needs to be set? Could you pls guide.

Regards,
Vivek

**Comment by michelson** [comment]
I will suggest that you check your browser console for errors, also have you set up the ENV vars in the .env file ?

**Comment by vivec80** [comment]
Yes, ENV vars are set for host, asset_host, WS, admin email and pwd as per the instructions in .env.
Looking at the browser console i found the below error:

Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/vivec80/chaskiq/app/javascript/packs/application.js: Unexpected token (22:4)

  20 | document.addEventListener('DOMContentLoaded', () => {
  21 |   ReactDOM.render(
> 22 |     <App />,
     |     ^
  23 |     document.body.appendChild(document.getElementById('main-page')),
  24 |   )
  25 | })
    at Parser._raise (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:742)
    at Parser.raiseWithData (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:735)
    at Parser.raise (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:729)
    at Parser.unexpected (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:8757)
    at Parser.parseExprAtom (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:10052)
    at Parser.parseExprSubscripts (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9602)
    at Parser.parseMaybeUnary (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9582)
    at Parser.parseExprOps (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9452)
    at Parser.parseMaybeConditional (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9425)
    at Parser.parseMaybeAssign (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9380)
    at Parser.parseExprListItem (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:10718)
    at Parser.parseCallExpressionArguments (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9790)
    at Parser.parseSubscript (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9696)
    at Parser.parseSubscripts (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9625)
    at Parser.parseExprSubscripts (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9608)
    at Parser.parseMaybeUnary (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9582)
    at Parser.parseExprOps (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9452)
    at Parser.parseMaybeConditional (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9425)
    at Parser.parseMaybeAssign (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9380)
    at Parser.parseExpression (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9332)
    at Parser.parseStatementContent (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:11210)
    at Parser.parseStatement (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:11081)
    at Parser.parseBlockOrModuleBlockBody (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:11656)
    at Parser.parseBlockBody (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:11642)
    at Parser.parseBlock (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:11626)
    at Parser.parseFunctionBody (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:10634)
    at Parser.parseArrowExpression (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:10603)
    at Parser.parseParenAndDistinguishExpression (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:10221)
    at Parser.parseExprAtom (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9947)
    at Parser.parseExprSubscripts (:3000/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9602)
    at Object../app/javascript/packs/application.js (application.css:1)
    at __webpack_require__ (bootstrap:725)
    at fn (bootstrap:100)
    at Object.0 (application.css:1)
    at __webpack_require__ (bootstrap:725)
    at bootstrap:792
    at bootstrap:792
./app/javascript/packs/application.js @ application.css:1
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ application.css:1
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
DevTools failed to load SourceMap: Could not load content for chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/js/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/js/intercom-link-expand-loader.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by michelson** [comment]
oh I see, it seems that you have to install js dependences `yarn install`

**Comment by vivec80** [comment]
Did that but still the same error :(

**Comment by michelson** [comment]
Try to run the asset compilation with `yarn dev`

**Comment by vivec80** [comment]
Tried that, failing to compile. Primarily 2 errors. One is same as what I was getting in browser. See below trace:

ERROR in ./app/javascript/client_messenger/messenger.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):

SyntaxError: /Users/vivec80/chaskiq/app/javascript/client_messenger/messenger.js: Unexpected token (947:11)



  945 |     const assignee = this.assignee()

  946 |   

> 947 |     return <HeaderAvatar>

      |            ^

  948 |               { assignee && 

  949 |                 <React.Fragment>

  950 |                   <img src={assignee.avatarUrl} />

    at Parser._raise (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:742:17)

    at Parser.raiseWithData (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:735:17)

    at Parser.raise (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:729:17)

    at Parser.unexpected (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:8757:16)

    at Parser.parseExprAtom (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:10052:20)

    at Parser.parseExprSubscripts (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9602:23)

    at Parser.parseMaybeUnary (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9582:21)

    at Parser.parseExprOps (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9452:23)

    at Parser.parseMaybeConditional (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9425:23)

    at Parser.parseMaybeAssign (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9380:21)



ERROR in ./app/javascript/packs/application.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):

SyntaxError: /Users/vivec80/chaskiq/app/javascript/packs/application.js: Unexpected token (22:4)



  20 | document.addEventListener('DOMContentLoaded', () => {

  21 |   ReactDOM.render(

> 22 |     <App />,

     |     ^

  23 |     document.body.appendChild(document.getElementById('main-page')),

  24 |   )

  25 | })

    at Parser._raise (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:742:17)

    at Parser.raiseWithData (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:735:17)

    at Parser.raise (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:729:17)

    at Parser.unexpected (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:8757:16)

    at Parser.parseExprAtom (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:10052:20)

    at Parser.parseExprSubscripts (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9602:23)

    at Parser.parseMaybeUnary (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9582:21)

    at Parser.parseExprOps (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9452:23)

    at Parser.parseMaybeConditional (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9425:23)

    at Parser.parseMaybeAssign (/Users/vivec80/chaskiq/node_modules/@babel/parser/lib/index.js:9380:21)

ℹ ｢wdm｣: Failed to compile.

**Comment by michelson** [comment]
umm... very strange, which node version are you using ? im my local dev machine I have `12.18.3` and in github action we test this with version `10.x`

**Comment by vivec80** [comment]
Its 12.16.1. Do I need to downgrade?

**Comment by vivec80** [comment]
Upgraded it to your version i.e 12.18.3. Still the same error as above..

**Comment by bensssyde** [comment]
@vivec80  I suggest you create a `.babelrc` file in the project root with below content then retry compile with  `yarn dev`
```
{
    "presets" : ["@babel/preset-env", "@babel/preset-react"]
}
```

**Comment by michelson** [comment]
There is a babel.config.js in the project too. But yeah it seems a babel compilation issue

**Comment by vivec80** [comment]
Thanks @bensssyde! That resolved the issue!
Now on to the next one :)..seems css is not loading well( ss attached ). Also, when i try to login with my admin credentials , it is not working..css gets broken further when i try to login
![Screenshot 2020-09-07 at 9 14 11 AM](https://user-images.githubusercontent.com/802218/92346490-8c97e600-f0ea-11ea-800c-e69bd6c248ed.png)
![Screenshot 2020-09-07 at 9 10 44 AM](https://user-images.githubusercontent.com/802218/92346501-91f53080-f0ea-11ea-82b1-eb75ef011929.png)

**Comment by michelson** [comment]
I think you will have to use the babel config from the babel.config.js file, is not clear to me why is failing

can you share the commands you use to start the server and the webpack dev server ?

**Comment by michelson** [comment]
this issue looks similar https://github.com/rails/webpacker/issues/749#issuecomment-328074888

**Comment by vivec80** [comment]
I am using 'bundle exec rails server' for staring the server and 'yarn dev' for webpack dev server

**Comment by vivec80** [comment]
Seems i will have to abandon this in view of no solution. We should have a better documentation is what I feel. Good Luck!

**Comment by michelson** [comment]
Sorry to hear that, let me know if you want to give this a try we could do a video call

**Comment by ghost** [comment]
hi all,
i know it says "closed" and i am a newbie here so i decided to write as i had the same problem and i tried several solutions including the steps mentioned in this page but it was not solved until i also used the URL: http://localhost:3000 instead of: http://127.0.0.1:3000 then i got a functional page instead of a blank one.
