### ISSUE TITLE
Heroku deploy fails

### ISSUE THREAD

**Issue by Reiszecke** [chaskiq/chaskiq#788]
Following the deploy link at https://dev.chaskiq.io/production-configuration/deploy-on-heroku it breaks after like 5 minutes:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/11237541/183265298-8b7717ee-468b-4369-a8a4-c27a2f778115.png">

In the log it mentions `ActiveRecord::StatementInvalid: PG::RaiseException: ERROR:  Extensions can only be created on heroku_ext schema`, https://stackoverflow.com/questions/73214844/error-extension-btree-gist-must-be-installed-in-schema-heroku-ext has a similar issue that apparently came up due to a Heroku change this week (?).

Full log below:

```
/app/vendor/bundle/ruby/2.7.0/gems/anyway_config-2.3.0/lib/anyway/type_casting.rb:111: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
/app/vendor/bundle/ruby/2.7.0/gems/anyway_config-2.3.0/lib/anyway/rbs.rb:40: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
`URLcrypt.key=` is deprecated. See the README on using environment variables with URLcrypt.
[Scout] [08/06/22 20:30:24 +0000 run.4492 (7)] INFO : Scout Agent [5.2.0] Initialized
[Scout] [08/06/22 20:30:24 +0000 run.4492 (7)] INFO : Not Loading Instruments
[Scout] [08/06/22 20:30:24 +0000 run.4492 (7)] INFO : Scout Agent [5.2.0] Installed
[Scout] [08/06/22 20:30:24 +0000 run.4492 (7)] INFO : Monitoring isn't enabled for the [production] environment.
[Scout] [08/06/22 20:30:24 +0000 run.4492 (7)] INFO : Deferring agent start. Standing by for first request
`Redis.current` is deprecated and will be removed in 5.0. (called from: /app/vendor/bundle/ruby/2.7.0/bundler/gems/nightfury-b9014eec30d9/lib/nightfury.rb:18:in `redis')
I, [2022-08-06T20:30:25.110108 #7]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of PG::RaiseException
rake aborted!
ActiveRecord::StatementInvalid: PG::RaiseException: ERROR:  Extensions can only be created on heroku_ext schema
CONTEXT:  PL/pgSQL function inline_code_block line 7 at RAISE
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:767:in `block in exec_no_cache'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:766:in `exec_no_cache'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:434:in `enable_extension'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/migration.rb:932:in `block in method_missing'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/migration.rb:900:in `block in say_with_time'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/migration.rb:900:in `say_with_time'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/migration.rb:921:in `method_missing'
/app/db/schema.rb:15:in `block in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/schema.rb:55:in `instance_eval'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/schema.rb:55:in `define'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/schema.rb:50:in `define'
/app/db/schema.rb:13:in `<main>'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:377:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:377:in `load_schema'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:482:in `block in load_schema_current'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:554:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:553:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:481:in `load_schema_current'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/railties/databases.rake:469:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/integrations/rake.rb:20:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:23:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli.rb:483:in `exec'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
/app/bin/bundle:5:in `load'
/app/bin/bundle:5:in `<main>'

Caused by:
PG::RaiseException: ERROR:  Extensions can only be created on heroku_ext schema
CONTEXT:  PL/pgSQL function inline_code_block line 7 at RAISE
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:767:in `block in exec_no_cache'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:766:in `exec_no_cache'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:434:in `enable_extension'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/migration.rb:932:in `block in method_missing'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/migration.rb:900:in `block in say_with_time'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/migration.rb:900:in `say_with_time'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/migration.rb:921:in `method_missing'
/app/db/schema.rb:15:in `block in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/schema.rb:55:in `instance_eval'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/schema.rb:55:in `define'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/schema.rb:50:in `define'
/app/db/schema.rb:13:in `<main>'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:377:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:377:in `load_schema'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:482:in `block in load_schema_current'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:554:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:553:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/tasks/database_tasks.rb:481:in `load_schema_current'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.3/lib/active_record/railties/databases.rake:469:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/integrations/rake.rb:20:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:23:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli.rb:483:in `exec'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
/app/bin/bundle:5:in `load'
/app/bin/bundle:5:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**Comment by michelson** [comment]
Hi, seems so the change was added a couple of days ago, 
here is the update with the solution https://devcenter.heroku.com/changelog-items/2446

**Comment by Reiszecke** [comment]
@michelson bro I have no idea what any of that means for this repo here, I can neither find `schema_name` nor `search_path` being referenced in this repo.

**Comment by joelbiffin** [comment]
For the time being there's a Monkey Patch listed here:

https://stackoverflow.com/questions/73214844/error-extension-btree-gist-must-be-installed-in-schema-heroku-ext/73273766#73273766
